//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDemo.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientDemo.ServiceReference1.codeUsers))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WorkService.Models.ServerMessage))]
    public partial class Entity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object OnClickField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowSortField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSelected {
            get {
                return this.IsSelectedField;
            }
            set {
                if ((this.IsSelectedField.Equals(value) != true)) {
                    this.IsSelectedField = value;
                    this.RaisePropertyChanged("IsSelected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object OnClick {
            get {
                return this.OnClickField;
            }
            set {
                if ((object.ReferenceEquals(this.OnClickField, value) != true)) {
                    this.OnClickField = value;
                    this.RaisePropertyChanged("OnClick");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowSort {
            get {
                return this.RowSortField;
            }
            set {
                if ((this.RowSortField.Equals(value) != true)) {
                    this.RowSortField = value;
                    this.RaisePropertyChanged("RowSort");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="codeUsers", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class codeUsers : ClientDemo.ServiceReference1.Entity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int departIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> lastSentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailpwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailtoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int departId {
            get {
                return this.departIdField;
            }
            set {
                if ((this.departIdField.Equals(value) != true)) {
                    this.departIdField = value;
                    this.RaisePropertyChanged("departId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> lastSent {
            get {
                return this.lastSentField;
            }
            set {
                if ((this.lastSentField.Equals(value) != true)) {
                    this.lastSentField = value;
                    this.RaisePropertyChanged("lastSent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mail {
            get {
                return this.mailField;
            }
            set {
                if ((object.ReferenceEquals(this.mailField, value) != true)) {
                    this.mailField = value;
                    this.RaisePropertyChanged("mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mailpwd {
            get {
                return this.mailpwdField;
            }
            set {
                if ((object.ReferenceEquals(this.mailpwdField, value) != true)) {
                    this.mailpwdField = value;
                    this.RaisePropertyChanged("mailpwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mailto {
            get {
                return this.mailtoField;
            }
            set {
                if ((object.ReferenceEquals(this.mailtoField, value) != true)) {
                    this.mailtoField = value;
                    this.RaisePropertyChanged("mailto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string number {
            get {
                return this.numberField;
            }
            set {
                if ((object.ReferenceEquals(this.numberField, value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDocumentService", CallbackContract=typeof(ClientDemo.ServiceReference1.IDocumentServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IDocumentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/GetData", ReplyAction="http://tempuri.org/IDocumentService/GetDataResponse")]
        string GetData(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/RegisNewUser", ReplyAction="http://tempuri.org/IDocumentService/RegisNewUserResponse")]
        WorkService.Models.ServerMessage RegisNewUser(ClientDemo.ServiceReference1.codeUsers user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/Login", ReplyAction="http://tempuri.org/IDocumentService/LoginResponse")]
        WorkService.Models.ServerMessage Login(string user, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/AddDiary", ReplyAction="http://tempuri.org/IDocumentService/AddDiaryResponse")]
        WorkService.Models.ServerMessage AddDiary(int userId, string title, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/GetResult", ReplyAction="http://tempuri.org/IDocumentService/GetResultResponse")]
        string GetResult();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentService/SetResult", ReplyAction="http://tempuri.org/IDocumentService/SetResultResponse")]
        void SetResult(int value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDocumentService/GetSessionId")]
        void GetSessionId();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDocumentService/CallbackAction")]
        void CallbackAction(string sessionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentServiceChannel : ClientDemo.ServiceReference1.IDocumentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentServiceClient : System.ServiceModel.DuplexClientBase<ClientDemo.ServiceReference1.IDocumentService>, ClientDemo.ServiceReference1.IDocumentService {
        
        public DocumentServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DocumentServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DocumentServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string GetData(string value) {
            return base.Channel.GetData(value);
        }
        
        public WorkService.Models.ServerMessage RegisNewUser(ClientDemo.ServiceReference1.codeUsers user) {
            return base.Channel.RegisNewUser(user);
        }
        
        public WorkService.Models.ServerMessage Login(string user, string pwd) {
            return base.Channel.Login(user, pwd);
        }
        
        public WorkService.Models.ServerMessage AddDiary(int userId, string title, string content) {
            return base.Channel.AddDiary(userId, title, content);
        }
        
        public string GetResult() {
            return base.Channel.GetResult();
        }
        
        public void SetResult(int value) {
            base.Channel.SetResult(value);
        }
        
        public void GetSessionId() {
            base.Channel.GetSessionId();
        }
    }
}
